name: family-tree

services:
  mongo:
    image: mongo:7-jammy
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: familytree
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
