on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: npm-and-bower
          path: |
            node_modules/
            app/bower_components/
      - run: npm install
      - run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: npm-and-bower
          path: |
            node_modules/
            app/bower_components/
      - run: npm install
      - run: npm run build
